### ISSUE TITLE
vsaa required to use lvsfunc.misc.source?

### ISSUE THREAD

**Issue by adworacz** [Irrational-Encoding-Wizardry/lvsfunc#150]
It appears that due to how the current `__init__.py` is setup, attempting to use `lvsfunc.misc.source` causes scripts to fail when `vsaa` is not installed.

Can we split up the imports so that `vsaa` is only imported when its used?

Example stacktrace:

```
2022-09-05 20:51:02.243: INFO: QSS file successfully loaded.
2022-09-05 20:51:02.243: INFO: Found version patches to be applied.
2022-09-05 20:51:02.243: INFO: Found application patches to be applied.
2022-09-05 20:51:02.404: ERROR: No module named 'vsaa'
2022-09-05 20:51:02.405: ERROR: Traceback (most recent call last):
  File "script.vpy", line 4, in <module>
    import lvsfunc as lvs
  File "/usr/lib/python3.10/site-packages/lvsfunc/__init__.py", line 12, in <module>
    from . import (
  File "/usr/lib/python3.10/site-packages/lvsfunc/aa.py", line 9, in <module>
    import vsaa
ModuleNotFoundError: No module named 'vsaa'
```

**Comment by adworacz** [comment]
Note also that the AUR build doesn't have the `vsaa` dependency marked.

**Comment by LightArrowsEXE** [comment]
`vsaa` is part of the `requirements.txt` and thus should be installed when the user installs/updates lvsfunc. The package should *always* be available unless you're using some other method to install it than python/pip. So no, this behaviour won't change. Just install the missing package.


> Note also that the AUR build doesn't have the `vsaa` dependency marked.

I don't maintain it, but I don't know if the person who does is still around anymore. Will look, and if he's too inactive to keep maintaining it, I'll remove the README section.  For the time being, I suggest just using pip.
