### ISSUE TITLE
find_scene_changes: display error

### ISSUE THREAD

**Issue by Ichunjo** [Irrational-Encoding-Wizardry/lvsfunc#62]
```py
from vapoursynth import core
from lvsfunc.render import find_scene_changes


clip1 = core.ffms2.Source('video1.mkv')
clip2 = core.ffms2.Source('video2.mkv')

find_scene_changes(nced1)
find_scene_changes(nced2)
```

```
>>>python script.py
Detecting scene changes... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2160 0.00% 0.00 fps -:--:--
Traceback (most recent call last):
  File "g:\script.py", line 9, in <module>
    find_scene_changes(nced1)
  File "C:\Users\Varde\AppData\Roaming\Python\Python39\site-packages\lvsfunc\render.py", line 262, in find_scene_changes
    clip_async_render(clip, callback=_cb)
  File "C:\Users\Varde\AppData\Roaming\Python\Python39\site-packages\lvsfunc\render.py", line 178, in clip_async_render
    p.start()
  File "C:\Users\Varde\AppData\Roaming\Python\Python39\site-packages\rich\progress.py", line 644, in start
    self.live.start(refresh=True)
  File "C:\Users\Varde\AppData\Roaming\Python\Python39\site-packages\rich\live.py", line 113, in start
    self.console.set_live(self)
  File "C:\Users\Varde\AppData\Roaming\Python\Python39\site-packages\rich\console.py", line 780, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
Core freed but 6 filter instance(s) still exis
```
Tested with last pip version

**Comment by Ichunjo** [comment]
It seems fixed at git master though

**Comment by LightArrowsEXE** [comment]
Closing as this does not appear to be an issue in master
